draft-lmbdhk-quic-multipath.md
Each line is limited to 72 characters.
=> [~] break long lines, no other modifications

draft-lmbdhk-quic-multipath.md
=> [~] replace multi-path with multipath

draft-lmbdhk-quic-multipath.md
=> [~] avoid idle timeout of paths

draft-lmbdhk-quic-multipath.md
(OK, so it's not the biggest contribution I've ever made, but I DID notice it, while reading the master branch ...
=> type - "None" for "nonce"

draft-lmbdhk-quic-multipath.md
=> Define path

draft-lmbdhk-quic-multipath.md
=> SPNS: Ack delay considerations

draft-ietf-quic-multipath.md
=> transport parameters in RFC9000 are unchanged

draft-ietf-quic-multipath.md
=> Text from Olivier about active paths

draft-ietf-quic-multipath.md
This text is mostly taken from PR #88 but with some edits
=> new text on recovery

draft-ietf-quic-multipath.md
=> cc must be per path

draft-ietf-quic-multipath.md
This text will be moved to the next section in PR #102. Therefore this PR needs to be merged together with PR #102.
=> Removing text about preferred_address

draft-ietf-quic-multipath.md
Add some implementation considerations to handle different PMTU sizes following the discussion on #98 . Feel free to add different implementation options here.
=> Add implementation considerations to handle different PMTU sizes

.github/in-solidarity.yml
=> Add in-solidarity-bot config

draft-ietf-quic-multipath.md
It's a grammar error fix in the aead section.
=> fix grammar error as suggested by Kulsk in issue 119

draft-ietf-quic-multipath.md
=> [~] fix server MUST validate paths before using them

draft-ietf-quic-multipath.md
=> [~] modification for path states in Section 4.3

draft-ietf-quic-multipath.md
=> Clarify path closure and stateless reset reception

draft-ietf-quic-multipath.md
Mostly fixing some English spellings and sentences, "Figure Figure"
and "Section Section" occurrences. There is no content change here.
=> Minor editorial changes

draft-ietf-quic-multipath.md
=> Add discussion about retiring DCID when there are still in-flight packets

draft-ietf-quic-multipath.md
=> add some text to refuse path initiation

draft-ietf-quic-multipath.md
=> [~] replace MP_CONNECTION_ERROR with TRANSPORT_PARAMETER_ERROR

draft-ietf-quic-multipath.md
=> Add entry for the PATH_STATUS frame in IANA

draft-ietf-quic-multipath.md
=> Fix enable_multipath values

draft-ietf-quic-multipath.md
=> New implementation consideration on keep alives

draft-ietf-quic-multipath.md
=> Remove identifier type

draft-ietf-quic-multipath.md
This is the first PR of 3-4 editorial passes I'm planning to do. This first PR only move existing text into the right place. I did not change anything in the text (except the section heading).
The next round will move some sections entirely (e.g. section on congestion control, RTT calculation, packet scheduling could maybe go into the implementation considerations) and then I'm planning to do a full edit pass at the end to check consistency. Would be great if we could review and merge this one soon, so I can move on with the next one. I'm keeping those PRs separately so it is easier to follow the changes.
=> Move most text of former PNS/CID section to where it belongs

draft-ietf-quic-multipath.md
=> Fix path closure example with path ID

draft-ietf-quic-multipath.md
=> Clarify supported scenarios

draft-ietf-quic-multipath.md
=> Remove PNS ID

draft-ietf-quic-multipath.md
Let's give the facts to the implementers, without providing too specific guidance neither.
Fix #183 and may also address #190.
=> update scheduling guidances

draft-ietf-quic-multipath.md
=> editorial pass on frames section

draft-ietf-quic-multipath.md
=> ACK_MP frames ack 0-RTT packets too

draft-ietf-quic-multipath.md
=> ECN counts are per-path, not per connection

draft-ietf-quic-multipath.md
=> PATH_ABANDON and PATH_STATUS are ack-eliciting

draft-ietf-quic-multipath.md
fixes #211 
This PR proposed to remove this sentence entirely, as I don't think it's needed.
=> remove sentence an retransmittable table frames

draft-ietf-quic-multipath.md
=> Use FRAME_ENCODING_ERROR instead

draft-ietf-quic-multipath.md
=> Remove must check CIDs on both sides

draft-ietf-quic-multipath.md
=> what if all path are stand-by?

draft-ietf-quic-multipath.md
=> Change handshake error type

draft-ietf-quic-multipath.md
=> [=] Delete unused reference

draft-ietf-quic-multipath.md
=> fix token ambiguity issues

draft-ietf-quic-multipath.md
remove last 0xbaba experimental number
=> ACK_MP: fix typo about experiments number

draft-ietf-quic-multipath.md
=> PATH_STANDBY/AVAILABLE can be sent for all issued DCIDs

draft-ietf-quic-multipath.md
=> All non-probing frames on new paths

draft-ietf-quic-multipath.md
=> recommend bundle ACK_MP with PATH_RESPONSE

draft-ietf-quic-multipath.md
=> clarify path validation on previously used paths

draft-ietf-quic-multipath.md
=> token usage

.note.xml, draft-ietf-quic-multipath.md
Smaller nits from my review. I *believe* these should be entirely editorial and uncontroversial. However, if there's anything you'd like me to lift into a separate PR for discussion, I will happily do so.
=> Editorial feedback by mbishop

draft-ietf-quic-multipath.md
A starting point for security considerations, not much, but we can continuously add cases.
=> First shot for Security Consideration

draft-ietf-quic-multipath.md
=> Recommendations regarding CID allocation and Path ID continuity

draft-ietf-quic-multipath.md
As discussed during the interim. This solves issue #313.
=> Rewrite the path close section to specify symmetric Abandon

draft-ietf-quic-multipath.md
=> Rename ACK_MP frame to MP_ACK

draft-ietf-quic-multipath.md
=> Spell out LIA

draft-ietf-quic-multipath.md
=> clarify error handling and normative language for max path id

draft-ietf-quic-multipath.md
=> AEAD limits and use of multiple nonces

draft-ietf-quic-multipath.md
=> More guidance on "standby"

draft-ietf-quic-multipath.md
=> limit initial_max_path to 2^32-1 and more explanation

draft-ietf-quic-multipath.md
=> stream boundaries of retransmissions

draft-ietf-quic-multipath.md
=> Specify details of MP_RETIRE_CONNECTION_ID

draft-ietf-quic-multipath.md
=> Editorial: fix error internal ref

draft-ietf-quic-multipath.md
=> Describe the effect of disable_active_migration more accurately

draft-ietf-quic-multipath.md
=> Editorial: add reference for MP_NEW_CONN_ID frame

draft-ietf-quic-multipath.md
=> SHOULD use MP frame for path ID 0

draft-ietf-quic-multipath.md
=> PATH_ABANDON on broken path

draft-ietf-quic-multipath.md
=> Remove MP_PROTOCOL_VIOLATION

draft-ietf-quic-multipath.md
=> Rename MP_* frames to PATH_*

draft-ietf-quic-multipath.md
=> Editorial: fix requirement of opening a new path

draft-ietf-quic-multipath.md
This change was discussed as part of PR #388
=> Delaying of PATH_RESPONSE

draft-ietf-quic-multipath.md
=> Clarify denying a path and move text

draft-ietf-quic-multipath.md
May be slightly easier to read than current spec on "new token".
Close #303
=> Propose new text for new token policy

draft-ietf-quic-multipath.md
I roughly looked through the issues and PRs but this list might still not be complete. But good to update for now!
=> Update Acknowledgement section

draft-ietf-quic-multipath.md
=> add ref to DPLPMTUD

draft-ietf-quic-multipath.md
=> Add implementation comments for key rotation.

draft-ietf-quic-multipath.md
=> Add more guidance on when to use PATH_ACK frames

draft-ietf-quic-multipath.md
=> packets without challenge are valid

draft-ietf-quic-multipath.md
=> new text on idle timeouts

draft-ietf-quic-multipath.md
=> fix TBD-03 -> TBD-04 for PATH_AVAILABLE

draft-ietf-quic-multipath.md
=> Typo "frames"

draft-ietf-quic-multipath.md
=> recommend use of new paths instead of migration

draft-ietf-quic-multipath.md
To solve issue #459 according to comments in IETF-121
=> Add new frame type: PATH_CIDS_BLOCKED frame

draft-ietf-quic-multipath.md
=> PATH_AVAILABLE is ack-eliciting

draft-ietf-quic-multipath.md
=> Update closure example

draft-ietf-quic-multipath.md
=> Improve text on IV and nonce

draft-ietf-quic-multipath.md
=> recommend one CID for each unused path

draft-ietf-quic-multipath.md
=> Don't send PATHS_BLOCKED/PATH_CIDS_BLOCKED frequently

draft-ietf-quic-multipath.md
=> Clarify use of PATH_CIDS_BLOCKED

draft-ietf-quic-multipath.md
I don't think we will need this section for the final RFC, do we?
=> Remove design consideration section

draft-ietf-quic-multipath.md
minor fix here; however we probably also need to check this in the rest of the doc.
=> add "in" before Section in intro

draft-ietf-quic-multipath.md
Please have a careful review as there have been some thing were old text was redundant or needed to be adopted/clarified based on newer text
=> editorial pass on section 3 (path management)

draft-ietf-quic-multipath.md
I also wonder if we should move this section into a subsection of the Abandon frame because this is only for this frame...?
=> shorter error code definition

draft-ietf-quic-multipath.md
=> clarification about when to send path-abandon

draft-ietf-quic-multipath.md
Proposed edits by Christian; slightly adapted
=> Edits on migration guidance section

draft-ietf-quic-multipath.md
=> Remove redundancy on use of PATH_NEW/RETIRE_CID frames

draft-ietf-quic-multipath.md
This also addresses an earlier comment made by @qdeconinck in PR #509
=> small editorial changes on "same 4-tuple" section

draft-ietf-quic-multipath.md
fixes #535 
This proposed note is an optional addition. It's also okay to not merge if we don't think it very useful
=> note on sending data frames on different paths

draft-ietf-quic-multipath.md
This addresses outstanding comments from Gorry's review (see email) and some edits he proposed in a follow-up email to me.
Thanks Gorry!
=> Some remaining small editorial improvements from Gorry

draft-ietf-quic-multipath.md
=> replace sequence value aead by 54321

draft-ietf-quic-multipath.md
=> 3x largest PTO for CONNECTION_CLOSE

draft-ietf-quic-multipath.md
Proposal for minor correction in Section 3.2.2
=> Typo in Section 3.2.2

draft-ietf-quic-multipath.md
=> replace lower-case may with might or could

draft-ietf-quic-multipath.md
=> calculate RTT if ACKs are not sent consistently

draft-ietf-quic-multipath.md
this was proposed by Tommy in issue #544
=> Rename PATH_BACKUP/AVAILABLE to PATH_STATUS_BACKUP/AVAILABLE

draft-ietf-quic-multipath.md
Clarify that a single 4-tuple can have multiple PMTU sizes. See #581
=> Clarify PMTU management - #581

draft-ietf-quic-multipath.md
=> remove "data packet"

draft-ietf-quic-multipath.md
=> Remove paragraph on uncoordinated close "rule"

draft-ietf-quic-multipath.md
fixes #550 (hopefully)
as proposed by @MikeBishop
=> sentence token/address tradeoff

draft-ietf-quic-multipath.md
fixes #556 
Minor rewording to hopefully make things more clear.
=> 3 PTOs "rule"

draft-ietf-quic-multipath.md
Typo: `MAX_PATH_ID_BLOCKED` -> `PATHS_BLOCKED`
=> Typo: MAX_PATH_ID_BLOCKED
