draft-lmbdhk-quic-multipath.md

The current text assumes that the server transport parameters are composed after seeing the client's proposal. As pointed out in issue #75, this is a deviation from standard QUIC practice. The proposed text fixes that and specifies what happens if both endpoints select option 3, "support both". In that case, option 2 "multiple number spaces" is selected.
Close #75

Do not assume real time formatting of server TP

---

README.md
draft-ietf-quic-multipath.md

Renames the markdown document and updates the README. The new links in the README that point to github-hosted pages might be dead for a while during the process.

Rename I-D post WG adoption

---

draft-ietf-quic-multipath.md

Attempt at moving 
Further, it is out of scope for
this document if the old address can also be used for multipath
after a client has migrated to the address provided in the preferred_address
transport parameter. However, it SHOULD NOT be assumed that it is
possible to use both addresses simultaneously without further confirmation
from the other host.
In the beginning of section where I think it would be more appropriate.

Moving second part of PR#99 to section 3

---

draft-ietf-quic-multipath.md

This PR is to resolve issue #1. The description of the path-closing figure is rephrased for better clarity. The path_id_type field in the PATH_ABANDON frame is also added in the figure to give an idea how the type is used. Moreover, one case for single PN is added (where the client receives zero-length CID while the server receives long CID). According to previous discussion, in the single PN case, only the client needs to send out a PATH_ABANDON. The server SHOULD stop sending new data on the path indicated by the PATH_ABANDON frame after receiving it. However, The client may want to repeat the
PATH_ABANDON frame if it sees the server continuing to send data. It is optional for the server to respond with a PATH_ABANDON after it receives a PATH_ABANDON frame from the client.

update path closure figure and add one case for single PN

---

draft-ietf-quic-multipath.md

This derives from the discussions on issue #96

First shot at a unified proposal

---

draft-ietf-quic-multipath.md

Replace "max_idle_timeout" with "a path's idle_period" in the Idle_Timeout Section and make sure that the idle_period is larger than 3 times the path's PTO.

fix max_idle_timeout issue in issue #95

---

draft-ietf-quic-multipath.md

Minor tweak. The text says that a path abandon "implies" retirement of the CID. Readers could be mislead and assume that they don't need to send a retire frame after sending abandon, when in fact they do.

Do not imply

---

draft-ietf-quic-multipath.md

For issue #125 , add some considerations for RTT computation in our single pns implementation. Not sure if it is easy enough to understand. Please feel free to change.

Add more explanation on ACK delay, RTT computation for single PNS

---

draft-ietf-quic-multipath.md

as this is already stated normatively in RFC900.
fixes #162

Do not use normative language for congestion control

---

draft-ietf-quic-multipath.md

In lot of places in the draft, we mention the "Path Identifier", which we define as the Destination Connection ID sequence number used over that path. It seems that maintaining the notion of "Path Identifier" causes a lot of confusion, so better keep things simple and mention CID sequence numbers directly.
Note that this implies that the related fields in
multipath-specific have been renamed to their "explicit" form. Some of these names are maybe a bit long, so we may shorten them if this does not introduce ambiguity.
Fix #169. Rewriting related section may also answer #181.

Remove mentions of the "Path Identifier"

---

draft-ietf-quic-multipath.md

fixes #160
As I added this text into the implementation consideration section, I on purpose did not use normative language. However, we might want to double check that the normative language we used elsewhere in the document is covering this appropriately.

Clarifications on connection migration

---

draft-ietf-quic-multipath.md

A new sentence is added to clarify that when a new CID is used, packet number space's largest_ack should be reset to None for the packet number encoding algorithm specified in RFC9000.

Add descriptions on resetting packet number  when a new CID is used

---

draft-ietf-quic-multipath.md

The current text says that one has to wait for a the retire frame or 3 PTOs. However (as also indicated in the states figure) this should be at least 3 PTOs. This PR fixes this inconsistency. Further is add a reference to the definition to PTO and replaces RTO with PTO where the wrong term is used. I believe all these fixes address straightforward mistakes, however, if discussion is needed, we can of course also open an issue.

Clarify path close and waiting for at least 3 PTOs

---

draft-ietf-quic-multipath.md

More specifically, if the receiver cannot process an old DCID seq number, it MUST ignore it (i.e., no error).
Fix #193. Also fix #137.

Make DCID sequence number considerations common to all multipath-specific frames

---

draft-ietf-quic-multipath.md

As a working group, we are spending efforts to prevent ossification (see QUIC v2 draft as an example).
I think it'd be inappropriate to have a statement that sounds as if we think that ossification is inevitable and that QUIC versions other than v1 is going to have lower penetration rate.

remove text that contradicts to the WG's effort trying to prevent ossification

---

draft-ietf-quic-multipath.md

The value of the transport parameter is a legacy of previous versions. Given the multipath support can be summarized as a boolean value, let's use a zero-length value TP.
Also updated the wire value of the TP, given its processing differs from the draft-04 TP.

enable_multipath as a zero-length transport parameter

---

draft-ietf-quic-multipath.md

Closes #221. As discussed in the issue, endpoints need to retain unused CIDs, otherwise they cannot respond to NAT rebinding.
Also removes a stale statement about zero-length CID.

Don't use all CIDs unless rebinding is a nonconcern

---

draft-ietf-quic-multipath.md

Closes #232.
The only state that can be discarded at PATH_ABONDON + 3PTO is that used for sending packets, as the states for receiving and acknowledging packets arriving on the abandoned path are expected to be retained until the receipt of RETIRE_CONNECTION_ID.
This PR clarifies that from the viewpoint of state machinery.

clarify the effect on transport machinery at PATH_ABANDON + 3PTO

---

draft-ietf-quic-multipath.md

1-RTT packets are packet types, not encryption levels

---

draft-ietf-quic-multipath.md

fixes #219 
Do we need to use normative language here?

MUST NOT store enable_multipath parameter

---

draft-ietf-quic-multipath.md

Specifically,
* forbid use of cipher suites with nonce below 12 bytes
* nonce calculation uses lower 32 bites of CID sequence number
* one packet protection key must not cover more than 2^32 CID sequence numbers
Closes #213. Closes #244.

clarify nonce usage

---

draft-ietf-quic-multipath.md

We should at least name Marten and Kazuho in the acknowledgement section. Who else?

Add some acks

---

draft-ietf-quic-multipath.md

fixes #132 
This proposed text updates the discussion of RTT computation and ACK_MP scheduling in the Example section, which is not normative. The proposed text reflects the discussion during the working group meeting in Yokohama, and aligns with the apparent consensus that emerged during the discussion.

Proposed text for RTT computation and ACK_MP scheduling

---

draft-ietf-quic-multipath.md

Close #202 
For frame types, this PR replaces the human generated prefix `0xbaba` by `0x15228c`, which is the most significant 24 bits of the MD5 hash of the string "QUIC Multipath" (`0x15228c615c39b7ecbe121d64958cd9ea`). The resulting codes become:
Value                                              | Frame Name          
---------------------------------------------------|--------------------
TBD-00 - TBD-01 (experiments use 0x15228c00-0x15228c01) | ACK_MP    
TBD-02 (experiments use 0x15228c05)                  | PATH_ABANDON   
TBD-03 (experiments use 0x15228c06)                  | PATH_STATUS 
For the error code, this PR replaces the human generated code `0xba00` by `0x1001d76d3ded42f3`, a 62 bit number that happens to match the first 64 bits of the MD5 hash of "QUIC …

replace 0xbaba by random numbers.

---

draft-ietf-quic-multipath.md

Closes #255. Specifically, this PR
* Clarifies that multipath frames will be use on the original path when the server provides both preferred_address and disable_active_migration TP and that only path establishment is prohibited until switching to the preferred address.
* Stops using normative clause for acknowledging what is specified in RFC 9000, adding a reference instead.

editorial cralification around preferred_address

---

draft-ietf-quic-multipath.md

switch to using 3xmaxPTO between key updates

---

draft-ietf-quic-multipath.md

send PATH_ABANDON after time-out on another path

---

draft-ietf-quic-multipath.md

As the design required revision of the entire draft, this PR attempts to be a start point.

[+] Explicit path identifier first shot

---

draft-ietf-quic-multipath.md

Also seems like you had a load of trailing whitespace that would hurt the linter's feelings.

Fix errors and warning related to references

---

draft-ietf-quic-multipath.md

I mainly merged the "Path identifier" section into the right place in the rest of the document. Having such a separate section did repeat the same things multiple time. That is usually very unfortunate because that means you have to change things in multiple places.
Further, some smaller editorial issue in the rest of the document.
This is only a first pass, I think we need more iterations.

Editorial pass on explicit Path ID

---

draft-ietf-quic-multipath.md

[+] Explicit Path ID: Clarify that endpoints use the same Path ID in both directions.

---

draft-ietf-quic-multipath.md

The term "endhost" appears ~8 times, while "endpoint" appears ~70 times. Let's consolidate, unless there's a deliberate distinction.

endhost -> endpoint

---

draft-ietf-quic-multipath.md

The sentence about key updates was removed as the key update text was removed in PR #358. Instead I propose to add sentence that explains the limit of the path ID to 2^32 - 1.

Clarify path ID limit for Nonce in intro

---

draft-ietf-quic-multipath.md

This section should be called "Path Status Management" because it about the path status. Path state is confusing because there is another section later on called "Path States" which outlines about the validating, active and closing states.

path state -> path status

---

draft-ietf-quic-multipath.md

This is the original proposal of Martin's PR: 
> There was a naming inconsistency here.
> 
> I went with one direction, which I think works best as it has a direct relation to the path identifier.  MAX_STREAMS uses a count because of the way in which streams are allocated odd/even.  That awkwardness we have for streams isn't necessary here.
This part is merged into the current branch to make the modification of transport parameter and frame have the same semantics and easier to review.

[=] Cleanup MAX_PATHS

---

draft-ietf-quic-multipath.md

This is an attempt to clean up the intro a bit, however, we could probably further cut down or move content in other sections respectively. As such this is a proposed first clean-up step that limit edits to the intro and overview section only.

Editorial: Merge of overview into intro & subsections

---

draft-ietf-quic-multipath.md

This text is not needed anymore, as this issue does exists as we now manage CIDs per path with MP_NEW/RETIRE_CIDS

There is always a valid CID now for each path

---

draft-ietf-quic-multipath.md

This PR try to solve the issue #324 and remove the outdated text.
As @martinthomson pointed out in PR #372, we don't have to use a count. This would help remove the ambiguity in the old draft version: 
- When endpoints negotiate a transport parameter value with N, but initial path(Path ID = 0) is also count into the number, the max available path id is actually N-1. It's weird and doesn't match the description of Max Path ID field inside MAX_PATH frame.

Rename transport parameter initial_max_paths to initial_max_path_id

---

draft-ietf-quic-multipath.md

There was a naming inconsistency here.
I went with one direction, which I think works best as it has a direct relation to the path identifier.  MAX_STREAMS uses a count because of the way in which streams are allocated odd/even.  That awkwardness we have for streams isn't necessary here.

Cleanup MAX_PATHS

---

draft-ietf-quic-multipath.md

According to PR #377 and PR #375, the examples in [Section 6](https://datatracker.ietf.org/doc/html/draft-ietf-quic-multipath-08#section-6) is outdated. Try to update the figures and keep examples compatible.

Rewrite outdated examples in Section 6

---

draft-ietf-quic-multipath.md

This is a simple PR designed to fix issue #378. It is mostly editorial, simply stating that multiple path sharing the same 4-tuple is just fine, and checking the draft to make sure we never say that a path is defined by a 4-tuple.

Multiple paths may use the same 4 tuple.

---

draft-ietf-quic-multipath.md

fixes #339 
This proposed editorial edit still mentions that packet numbers are per path. However, alternative we could also remove this second sentence entirely as it is normal RFC9000 behavior that retirement of a CID will not remove any path ressources.

Editorial minor change to not repeat RFC9000 behaviour

---

draft-ietf-quic-multipath.md

fixes #347 and some left-over on migration that do not apply anymore

remove probing concept and text on migration

---

draft-ietf-quic-multipath.md

This is an attempt to fix issue #342. I have added the MAX_PATH_ID_BLOCKED frame and related texts. Note that the same Path ID is used in both directions to address a path so the path identifier can be either limited by the sender or its peer. We should treat the two scenario differently and MAX_PATH_ID_BLOCKED should be used when the limit is set by the peer.

Add MAX_PATH_ID_BLOCKED frame and related texts

---

draft-ietf-quic-multipath.md

Attempt at providing further guidance and point out risks if both endpoints attempt to close one of the duplicate paths at the same time. Also mention that there will be cases where having "duplicate" path is intentional, maybe because they have different diffserv markings.
Close #378

Do not delete both duplicate paths

---

draft-ietf-quic-multipath.md

fixes #409
"active path" was used for both: a path that is open or actively used. This PR removed the word active and uses either "open" or "usable" to distinguish these cases.
If more appropriate it might also use the term "established" for an open path. Is that okay, or should we only use "open"?

remove the term "active path" as it was not well defined

---

draft-ietf-quic-multipath.md

Connection ID sequence number space starts at 0 for all paths

---

draft-ietf-quic-multipath.md

At least #428 (remove MP error) and #402 (PATH_BLOCKED) are breaking changes and #445 will be as well.

Increasing the transport parameter value

---

draft-ietf-quic-multipath.md

To fix issue #457. 
We could add some implementation guidance, but how aggressive depends on the implementations. (according to the discussion in IETF 121.)

Add guidance on handling of PTO

---

draft-ietf-quic-multipath.md

Fix issue #461. 
Generally the PATH_BLOCKED frame is informational and doesn't change the state of the peer.

Add clarification for PATHS_BLOCKED frame.

---

draft-ietf-quic-multipath.md

To fix issue #414, according to the discussion during IETF 121.

Add two more specific error codes for path abandon frame

---

draft-ietf-quic-multipath.md

I created this PR based on the discussion in (the now-closed) PR #473.
This is a slight change of the normative recommendation as it generally recommends to send the PATH_ABANDON on another path.
I understood that this is what we want to recommend but if not, we cannot also not apply this PR. Please comment!

always recommend to send path_abandon on another path

---

draft-ietf-quic-multipath.md

Note that path state cannot be removed without reception of PATH_ABANDON

---

draft-ietf-quic-multipath.md

this PR is a clarification based on the discussion in issue #454. Of course it's optimal to add this recommendation or not. However, it's in the implementation considerations section and I think at least noting the issue is a good thing.

acks are not congestion control -> be careful

---

draft-ietf-quic-multipath.md

As we have add new frame type PATH_CIDS_BLOCKED frame, we'd need a new transport parameter type.
BTW, as the transport parameter type is hex value, I used 0x0c for draft-12.

Update transport parameter for draft-12

---

draft-ietf-quic-multipath.md

It is the loss detection that is reused as is. MTU is on the QUIC packet level. Wrong plural on some frame section headers.

Editorial fixes

---

draft-ietf-quic-multipath.md

Aligning error code with RFC 9000. 
RFC 9000 states: "An endpoint MUST treat receipt of a frame in a packet type that is not permitted as a connection error of type PROTOCOL_VIOLATION."

Error code for receiving MP specific frame in other than 1-RTT packet

---

draft-ietf-quic-multipath.md

I have some editorial proposals.
1. Introduction
'packets' have not been mentioned before. --> 'QUIC packets' instead of 'such packets'
3. Path Management
No other way to start using multiple paths was presented before. --> Removing 'also'
3.3.2. Handling PATH_ACK for abandoned paths
As far as I understand the 'other packets' are a subset of the unacknowledged packets. --> 'Some of these' instead of 'Some other'

Editorial proposals

---

draft-ietf-quic-multipath.md

The tranport parameter was updated in the entry for the Quic Transport Parameters registry in  e26c2ef3ec1331b9f5af5d838af5cb267c8f5ed9 without updating the corresponding entry in the Handshake Negotiation and Transport Parameter section.

Make initial_max_path_id transport parameter consistent.

---

draft-ietf-quic-multipath.md

fixes #489 
This PR is a first PR of an editorial pass that only implements the new structure as proposed in PR #488. It does not change the content, despite some minor edits e.g. where redundant sentences were detected during the re-org, as well as some of the heading, plus adding new headings respectively.

Restructuring

---

draft-ietf-quic-multipath.md

This PR is an editorial pass of the intro. The aim is to provide a shorter, more clear text. This PR does not (really) modify the subsections of the intro, however, we could consider if sec 1.1. and maybe also the others should simply be removed...?

Shorter intro

---

draft-ietf-quic-multipath.md

This is not a full path on the implementation guidance section but it removes/merges one subsection and moves some sections around to align content better. However, there might be some editorial improvement needed on the rest of the text still.

initial pass - (re)move subsections in impl guidance sec

---

draft-ietf-quic-multipath.md

new paragraph on use cases in intro

---

draft-ietf-quic-multipath.md

fixes #510 
this patch replaces "path identifier" with path ID (expect in the field names) and also uses lower case "p" align with lower case c for connection ID in RFC9000

use only path ID

---

draft-ietf-quic-multipath.md

Here are a bunch of changes that I think cover all my corner cases of what the IETF has STD'ed/what would be regarded as EXP, and the caveats, while hopefully not constraining the use of MP-QUIC. I am super happier about the idea that this appears in the intro, rather than the spec.

Text proposed to address scope/expectation

---

draft-ietf-quic-multipath.md

We adjusted the terminology a while back to rather use open (as active includes path with issued path IDs that are not open yet). I used the terminology wrong when I added this sentence with the editorial pass. So fixing this now.

align terminology: active paths -> open paths

---

draft-ietf-quic-multipath.md

fixes #546
Proposed rewrite by @huitema to make it more clear that using the same path does not automatically imply sending a PATH_RESPONSE

using the same path ID, also for PATH_RESPONSE
